name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Build
        run: |
          rustup default nightly
          wasm-pack build --release
      - name: Update package.json name
        run: |
          cd pkg
          echo "`jq '.name = "@tangibl/topcodes-wasm"' package.json`" > package.json
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Publish to NPM
        run: |
          cd pkg
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
